### ISSUE TITLE
Prompt for Generating topic entities

### ISSUE THREAD

**Issue by schlabrendorff** [GasolSun36/ToG#6]
Hi! Thank you very much for your work. 
In your paper you write "ToG first prompts LLMs to automatically extract the topic entities in question and gets the top-N topic entities", but could not find the prompt, which you used to extract those topic entities?
In the repository they seem to be already hard-coded in the dataset JSONs due to a previous pre-processing step?

Could you describe how you extracted the topic entities?

**Comment by GasolSun36** [comment]
Yes, we use LLM to automatically identify the topic entity in the question. We used about 6-shot-cot and in-context learning. You can try to write the prompt yourself, it is pretty simple. We extracted the entity in this step directly into the data set in advance, so you can directly use it without preprocess.
