### ISSUE TITLE
 Issue with id2entity_name_or_type Function: SPARQL Query Handling

### ISSUE THREAD

**Issue by FUTUREEEEEE** [GasolSun36/ToG#7]
Hi, 
Thanks for sharing the code.

The id2entity_name_or_type function seems not function as expected due to variable overwriting. 

https://github.com/GasolSun36/ToG/blob/5badd58e7a2b596f2344c64f460383bd6e616594/ToG/freebase_func.py#L35

Is that right if I rewrite into this ? Thanks.

`def id2entity_name_or_type(entity_id):
    sparql_txt = sparql_id % (entity_id, entity_id)
    sparql = SPARQLWrapper(SPARQLPATH)
    sparql.setQuery(sparql_txt)`

**Comment by GasolSun36** [comment]
Hi，
The previous codebase version did have some minor bugs, which have been fixed. Please refer to the official repo.
https://github.com/IDEA-FinAI/ToG
