### ISSUE TITLE
 Request for CMD to Reproduce Results on WebQSP with Chat-GPT-3.5

### ISSUE THREAD

**Issue by FUTUREEEEEE** [GasolSun36/ToG#8]
Hello,

I am trying to reproduce the results on WebQSP using Chat-GPT-3.5, but I am facing some challenges with the provided command. I find that the exploration process is sensitive to the temperature. I was wondering if you could provide the correct command to reproduce the results successfully.

I currently use `python main_freebase.py --dataset webqsp --max_length 256 --temperature_exploration 1 --temperature_reasoning 0 --width 3 --depth 2 --remove_unnecessary_rel True --LLM_type gpt-3.5-turbo --opeani_api_keys sk-xxxx --num_retain_entity 5 --prune_tools llm`

Thank you!

**Comment by GasolSun36** [comment]
Hi,
please follow this sh command and use the latest codebase at official repo: [https://github.com/IDEA-FinAI/ToG](https://github.com/IDEA-FinAI/ToG)
```sh
python main_freebase.py \  # if you wanna use Wikidata as KG source, run main_wiki.py
--dataset webqsp \ # dataset your wanna test, see ToG/data/README.md
--max_length 256 \ 
--temperature_exploration 0.4 \ # the temperature in exploration stage.
--temperature_reasoning 0 \ # the temperature in reasoning stage.
--width 3 \ # choose the search width of ToG, 3 is the default setting.
--depth 3 \ # choose the search depth of ToG, 3 is the default setting.
--remove_unnecessary_rel True \ # whether removing unnecessary relations.
--LLM_type gpt-3.5-turbo \ # the LLM you choose
--opeani_api_keys sk-xxxx \ # your own api keys, if LLM_type == llama, this parameter would be rendered ineffective.
--num_retain_entity 5 \ # Number of entities retained during entities search.
--prune_tools llm \ # prune tools for ToG, can be llm (same as LLM_type), bm25 or sentencebert.
```
