### ISSUE TITLE
Linking topic entities to KG

### ISSUE THREAD

**Issue by alomrani** [GasolSun36/ToG#9]
Hi,

Once you generate the initial topic entities using the LLM, how do you find the corresponding entities in the KG? The LLM could output entities that do not exist in the KG. Also, what is the prompt used to find the topic entities?

Thanks,
Mohammad

**Comment by GasolSun36** [comment]
(1) After finding the entity, it can be converted through the API `label2qid` we defined https://github.com/GasolSun36/ToG/blob/main/Wikidata/simple_wikidata_db/db_deploy/client.py
(2) It is true that in some samples in some data sets, there may be no entity, or the entity cannot be identified. At this time, we samplely leave the topic entity blank, and use CoT by default to solve this problem.
(3) You can write the prompt of find topic entity yourself by introducing few-shot and CoT. We have saved the topic entity into the data set under the `data` folder in advance, please view it directly.
